---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1576475/public_html/
    - mkdir -p /home/u1576475/desa-johunut/
    - cp -r ./* /home/u1576475/desa-johunut/
    - cp -rf ./public/index-deploy.php ./public/index.php
    - cp -r ./public/* $DEPLOYPATH
